name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v7

      # 2. Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24' # Change to your required Go version

      # 3. Install dependencies
      - name: Install dependencies
        run: go mod download

      # 4. Run tests
      - name: Run tests
        run: go test -v -race ./...

      # 5. Build application
      - name: Build binary
        run: go build -v ./...
